apiVersion: v1
kind: Service
metadata:
  name: details-{{ .Values.details.version }}
  labels:
    app: details
    service: details
    version: "{{ .Values.details.version }}"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: details
    version: "{{ .Values.details.version }}"
