apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.bookinfo.appName }}"
  namespace: "{{ .Values.bookinfo.namespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "{{ .Values.bookinfo.namespace }}"
    server: "{{ .Values.spec.destination.server }}"
  project: "{{ .Values.spec.project }}"
  source:
    path: bookinfo
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.revision }}"
