apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.spec.deployA.appName }}"
  namespace: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: bookinfo
    repoURL: https://github.com/thiagonache/argocd-apps
    targetRevision: HEAD
