apiVersion: v1
kind: Service
metadata:
  name: ratings-{{ .Values.ratings.version }}
  labels:
    app: ratings
    service: ratings
    version: "{{ .Values.ratings.version }}"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings
    version: "{{ .Values.ratings.version }}"
