##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-{{ .Values.productpage.version }}
  labels:
    app: productpage
    service: productpage
    version: "{{ .Values.productpage.version }}"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
    version: "{{ .Values.productpage.version }}"
