##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-{{ .Values.productpage.version }}
  labels:
    app: productpage
    service: productpage
    version: "{{ .Values.productpage.version }}"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
    version: "{{ .Values.productpage.version }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage-{{ .Values.productpage.version }}
  labels:
    account: productpage
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: productpage-{{ .Values.productpage.version }}
  labels:
    app: productpage
    version: "{{ .Values.productpage.version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: "{{ .Values.productpage.version }}"
  template:
    metadata:
      labels:
        app: productpage
        version: "{{ .Values.productpage.version }}"
    spec:
      serviceAccountName: bookinfo-productpage-{{ .Values.productpage.version }}
      containers:
        - name: productpage
          image: docker.io/istio/examples-bookinfo-productpage-{{ .Values.productpage.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
canary:
  steps:
  - setWeight: 20
  - pause: {}
---

