##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings-{{ .Values.ratings.version }}
  labels:
    app: ratings
    service: ratings
    version: "{{ .Values.ratings.version }}"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings
    version: "{{ .Values.ratings.version }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings-{{ .Values.ratings.version }}
  labels:
    account: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-{{ .Values.ratings.version }}
  labels:
    app: ratings
    version: "{{ .Values.ratings.version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: "{{ .Values.ratings.version }}"
  template:
    metadata:
      labels:
        app: ratings
        version: "{{ .Values.ratings.version }}"
    spec:
      serviceAccountName: bookinfo-ratings-{{ .Values.ratings.version }}
      containers:
        - name: ratings
          image: docker.io/istio/examples-bookinfo-ratings-{{ .Values.ratings.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
---

