apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-{{ .Values.reviews.version }}
  labels:
    app: reviews
    version: "{{ .Values.reviews.version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: "{{ .Values.reviews.version }}"
  template:
    metadata:
      labels:
        app: reviews
        version: "{{ .Values.reviews.version }}"
    spec:
      serviceAccountName: bookinfo-reviews-{{ .Values.reviews.version }}
      containers:
        - name: reviews
          image: docker.io/istio/examples-bookinfo-reviews-{{ .Values.reviews.version }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: wlp-output
              mountPath: /opt/ibm/wlp/output
      volumes:
        - name: wlp-output
          emptyDir: {}
        - name: tmp
          emptyDir: {}
