apiVersion: v1
kind: Service
metadata:
  name: reviews-{{ .Values.reviews.version }}
  labels:
    app: reviews
    service: reviews
    version: "{{ .Values.reviews.version }}"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: reviews
    version: "{{ .Values.reviews.version }}"
